/*
 * jFCPlib-high-level-client - GetRequestResult.java -
 * Copyright © 2008 David Roden
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

package net.pterodactylus.fcp.highlevel;

import net.pterodactylus.fcp.Persistence;
import net.pterodactylus.fcp.PersistentGet;
import net.pterodactylus.fcp.Priority;
import net.pterodactylus.fcp.ReturnType;
import net.pterodactylus.fcp.Verbosity;

/**
 * A Get result result is generated by {@link HighLevelClient#getRequests()}.
 * 
 * @author David ‘Bombe’ Roden &lt;bombe@freenetproject.org&gt;
 */
public class GetRequestResult extends RequestResult {

	/** The PersistentGet FCP message. */
	private final PersistentGet persistentGet;

	/**
	 * Creates a new Get request result.
	 * 
	 * @param persistentGet
	 *            The PersistentGet message wrapped by this result
	 */
	public GetRequestResult(PersistentGet persistentGet) {
		super(persistentGet.getIdentifier());
		this.persistentGet = persistentGet;
	}

	/**
	 * Returns the client token associated with the request.
	 * 
	 * @return The client token
	 * @see net.pterodactylus.fcp.PersistentGet#getClientToken()
	 */
	public String getClientToken() {
		return persistentGet.getClientToken();
	}

	/**
	 * Returns the filename of the request.
	 * 
	 * @return The filename
	 * @see net.pterodactylus.fcp.PersistentGet#getFilename()
	 */
	public String getFilename() {
		return persistentGet.getFilename();
	}

	/**
	 * Returns the maximum number of retries for the request.
	 * 
	 * @return The maximum number of retries
	 * @see net.pterodactylus.fcp.PersistentGet#getMaxRetries()
	 */
	public int getMaxRetries() {
		return persistentGet.getMaxRetries();
	}

	/**
	 * Returns the persistence level of the request
	 * 
	 * @return The persistence level
	 * @see net.pterodactylus.fcp.PersistentGet#getPersistence()
	 */
	public Persistence getPersistence() {
		return persistentGet.getPersistence();
	}

	/**
	 * Returns the priority of the request.
	 * 
	 * @return The priority
	 * @see net.pterodactylus.fcp.PersistentGet#getPriority()
	 */
	public Priority getPriority() {
		return persistentGet.getPriority();
	}

	/**
	 * Returns the return type of the request.
	 * 
	 * @return The return type of the request
	 * @see net.pterodactylus.fcp.PersistentGet#getReturnType()
	 */
	public ReturnType getReturnType() {
		return persistentGet.getReturnType();
	}

	/**
	 * Returns the temporary filename of the request.
	 * 
	 * @return The temporary filename
	 * @see net.pterodactylus.fcp.PersistentGet#getTempFilename()
	 */
	public String getTempFilename() {
		return persistentGet.getTempFilename();
	}

	/**
	 * Returns the URI of the request.
	 * 
	 * @return The URI of the request
	 * @see net.pterodactylus.fcp.PersistentGet#getURI()
	 */
	public String getURI() {
		return persistentGet.getURI();
	}

	/**
	 * Returns the verbosity of the request.
	 * 
	 * @return The verbosity of the request
	 * @see net.pterodactylus.fcp.PersistentGet#getVerbosity()
	 */
	public Verbosity getVerbosity() {
		return persistentGet.getVerbosity();
	}

	/**
	 * Returns whether this request is on the global queue.
	 * 
	 * @return <code>true</code> if the request is on the global queue,
	 *         <code>false</code> if it is on the client-local queue
	 * @see net.pterodactylus.fcp.PersistentGet#isGlobal()
	 */
	public boolean isGlobal() {
		return persistentGet.isGlobal();
	}

}
